apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-data-loader
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
              - key: nautilus.io/reservation
                operator: In
                values:
                - sage
      tolerations:
      - key: nautilus.io/reservation
        operator: Equal
        value: sage
        effect: NoSchedule
      containers:
        - name: benchmark-data-loader
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1

