apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inquire-results-pvc
  labels:
    benchmark: inquire
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

