apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  template:
    spec:
      containers:
        - name: benchmark-job
          env:
            # Vector DB configuration (Weaviate)
            - name: WEAVIATE_HOST
              value: "dev-weaviate.sage.svc.cluster.local"
            # Inference server configuration (Triton)
            - name: TRITON_HOST
              value: "dev-triton.sage.svc.cluster.local"
            # S3 upload configuration (override base defaults for this benchmark)
            - name: S3_PREFIX
              value: "dev-metrics/inquire"
            - name: LOG_LEVEL
              value: "DEBUG"
