apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
spec:
  template:
    spec:
      containers:
        - name: benchmark-job
          env:
            # Vector DB configuration (Weaviate) - prod environment
            - name: WEAVIATE_HOST
              value: "prod-weaviate.sage.svc.cluster.local"
            # Inference server configuration (Triton) - prod environment
            - name: TRITON_HOST
              value: "prod-triton.sage.svc.cluster.local"
            # S3 upload configuration (override base defaults for this benchmark)
            - name: S3_PREFIX
              value: "prod-metrics/inquire"
            - name: LOG_LEVEL
              value: "INFO"
