apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-data-loader
spec:
  template:
    spec:
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: prod-huggingface-pvc

