apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-pvc
  labels:
    app: huggingface-pvc
  namespace: sage
spec:
  storageClassName: rook-ceph-block-central
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi